### ISSUE TITLE
TTGO and app shows different altitudes for balloon in the same position

### ISSUE THREAD

**Issue by eben80** [dl9rdz/rdzwx-go#2]
Hi,
I don't know if the altitudes are calculated differently, but I was consistently seeing different values for the altitude on the TTGO screen and the readout on the app.

**Comment by dl9rdz** [comment]
Yes this is intentional (suggestions on how to make this more explicit in the UI are welcome)

On the ESP32 its just the raw GPS ellipsoid height.
 
On the App its the true EGM96 geoid height (above see level), because that's what is expected for the prediction API and also what matches the height levels in the map...

**Comment by eben80** [comment]
OK I understand so what is displayed on the app should coincide with whatever is shown as elevation for those 2d coordinates on maps. Does that mean that that data comes from the map and is not calculated in real-time from balloon GPS?

**Comment by dl9rdz** [comment]
The app contains the EGM96 database (see https://en.wikipedia.org/wiki/Earth_Gravitational_Model) that describes the difference between GPS height and Geoid height, so the data received from the radiosonde is adjusted by the offset obtained from the database (around 40m in Europe).

So if a radiosonde is lying on the ground, then yes, then the displayed height should match the height from the map (+/- accuracy of the radiosonde GPS).

**Comment by eben80** [comment]
Thank you very much for that explanation. I don't have any suggestions for UI but I guess if it is just mentioned somewhere in the Wiki or app legend, it would be enough to inform users.
