### ISSUE TITLE
apk downlaod

### ISSUE THREAD

**Issue by pedjas** [dl9rdz/rdzwx-go#9]
Where from could apk be downloaded? Al I can find is Windows exe file.

**Comment by dl9rdz** [comment]
Releases v1.0.6

(not the experimental thing which is.... experimental for running in a pc. incomplete, just for testing)

**Comment by pedjas** [comment]
Aha! Thanks, now I found it.

**Comment by dl9rdz** [comment]
Closing this issue. 
The experimental thing is now marked such that the 1.0.6 release shows on top.

Maybe I will have some time to release a 1.1 version in the next weeks...
